/* Recipe planning stays entirely local in the browser; only household choices are shared. */
let foodPane='plan', recipeContext=null, recipeSearch='', recipeProtein='all', recipeQuick=false, recipeFaves=false;
const mealNames={breakfast:'Breakfast for us',child:'Little one’s lunch',lunch:'Lunch for us',dinner:'Dinner together'};
const foodEmoji={Eggs:'🥚',Chicken:'🍗',Fish:'🐟',Prawns:'🦐',Beef:'🥘',Lamb:'🥘',Paneer:'🧀',Tofu:'🌿',Lentils:'🥣',Beans:'🫘'};
const recipeById=id=>RECIPES.find(r=>r.id===id);
function isAllowed(r,s=state){return !r.allergens.some(a=>(s.foodPrefs?.excludedAllergens||[]).includes(a));}
function recipeFor(day,slot){const m=currentWeek().meals[day];const ref=m?.recipes?.[slot];const r=recipeById(ref?.id);return r&&r.title===m[slot]?r:null;}
function mealServings(w,day,slot){return slot==='child'?1:slot==='lunch'?Math.max(1,w.work[day].filter(v=>v==='home').length):2;}
function foodHome(){
 return `<div class="food-toolbar"><button data-food-pane="plan" class="${foodPane==='plan'?'selected':''}" aria-pressed="${foodPane==='plan'}">Our menu</button><button data-food-pane="library" class="${foodPane==='library'?'selected':''}" aria-pressed="${foodPane==='library'}">64 recipes</button><button data-food-pane="shop" class="${foodPane==='shop'?'selected':''}" aria-pressed="${foodPane==='shop'}">Groceries</button></div>${foodPane==='shop'?groceryView():foodPane==='library'?libraryLanding():mealPlanView()}`;
}
function mealPlanView(){const w=currentWeek(),m=w.meals[selected];return `<section class="food-intro"><span class="eyebrow">LESS DECIDING. MORE DELICIOUS.</span><h2>Something good is cooking.</h2><p>Flavour-first meals, with the thinking already done.</p><button class="button lime" data-food-action="plan">✦ Fill the week’s empty slots</button></section><div class="menu-cards">${Object.keys(mealNames).map(slot=>{const r=recipeFor(selected,slot);return `<section class="card menu-card"><div class="card-header"><div><span class="eyebrow">${esc(slot==='child'?`${state.child}’s lunch`:mealNames[slot])}</span><h3>${esc(m[slot]||'A tasty little possibility')}</h3></div><span class="food-sticker" aria-hidden="true">${r?foodEmoji[r.protein]:slot==='breakfast'?'☀️':slot==='child'?'🥣':'🍽️'}</span></div>${r?`<p class="recipe-meta">${r.minutes} min · ${esc(r.cuisine)} · ${m.recipes[slot].servings} ${slot==='child'?'small portion':'serving'}${m.recipes[slot].servings===1?'':'s'}</p>`:'<p class="recipe-meta">Pick a recipe. We’ll remember the ingredients.</p>'}${slot==='child'?`<p class="kindergarten-note">Kindergarten: ${esc(w.kindergarten?.[selected]||'Menu not added yet')}</p>`:''}<div class="meal-card-actions">${r?`<button class="button light" data-recipe-open="${r.id}" data-slot="${slot}">Cook this →</button>`:''}<button class="button ${r?'ghost':'light'}" data-recipe-pick="${slot}">${m[slot]?'Swap recipe':'Choose a recipe'}</button><button class="text-button" data-meal-slot="${slot}">Write my own</button></div>${r?`<button class="text-button" data-meal-portions="${slot}">Change portions</button>`:''}</section>`;}).join('')}</div><section class="card kindergarten-card"><h3>The kindergarten lunch brief</h3><p>Check their app once a week, then match the main idea with a lunch your little one knows.</p><button class="button light" data-food-action="kindergarten">Add the kindergarten menu</button></section><button class="text-button" data-food-action="preferences">Ingredients to avoid & food notes</button>`;}
function libraryLanding(){return `<section class="food-intro"><span class="eyebrow">YOUR LITTLE RECIPE BOOK</span><h2>Big flavour. Fewer “what ifs.”</h2><p>48 adult recipes + 16 toddler lunches. South Indian favourites, warm Middle Eastern spices, and gentle Southeast Asian flavours.</p></section><div class="recipe-doorways"><button data-recipe-pick="breakfast"><span>🥚</span><strong>Breakfast for us</strong><small>12 savory starts</small></button><button data-recipe-pick="dinner"><span>🍋</span><strong>Lunch & dinner</strong><small>36 ways out of a rut</small></button><button data-recipe-pick="child"><span>🥣</span><strong>Little lunches</strong><small>16 soft, balanced ideas</small></button><button data-food-action="favorites"><span>♡</span><strong>Our keepers</strong><small>${(state.recipeFavorites||[]).length} saved favourites</small></button></div><div class="food-note">No pizza, raw seafood, fish sauce or shrimp paste. Adult meals centre on protein and vegetables; exact macros haven’t been calculated. Toddler lunches follow a separate balanced approach.</div><button class="text-button" data-food-action="preferences">Ingredients to avoid & food notes</button>`;}
function recipeCandidates(){const slot=recipeContext.slot;return RECIPES.filter(r=>(recipeContext.all||r.slots.includes(slot))&&isAllowed(r)).filter(r=>recipeProtein==='all'||r.protein===recipeProtein).filter(r=>!recipeQuick||r.minutes<=25).filter(r=>!recipeFaves||(state.recipeFavorites||[]).includes(r.id)).filter(r=>(r.title+' '+r.cuisine+' '+r.ingredients.map(i=>i.name).join(' ')).toLowerCase().includes(recipeSearch.toLowerCase()));}
function recipePicker(slot,all=false){recipeContext={slot,day:selected,all};recipeSearch='';recipeProtein='all';recipeQuick=false;recipeFaves=all;modal(slot==='child'?`${esc(state.child)}’s lunch ideas`:'Find something delicious',`<div class="recipe-controls"><label>Search recipes<input type="search" id="recipe-search" placeholder="Try cauliflower, eggs, Kerala…" autocomplete="off"></label><label>Protein<select id="recipe-protein"><option value="all">Any protein</option>${[...new Set(RECIPES.filter(r=>all||r.slots.includes(slot)).map(r=>r.protein))].map(p=>`<option>${p}</option>`).join('')}</select></label><div class="recipe-filters"><label class="check-label"><input id="recipe-quick" type="checkbox">25 minutes or less</label><label class="check-label"><input id="recipe-faves" type="checkbox" ${all?'checked':''}>Our favourites</label></div></div>${slot==='child'?'<p class="food-note">Soft textures, starchy foods and no added sugar. Check allergens and the kindergarten’s food rules before packing.</p>':''}<div id="recipe-results" aria-live="polite"></div>`,()=>false);$('#dialog').classList.add('recipe-dialog');updateRecipeResults();}
function updateRecipeResults(){const list=recipeCandidates();$('#recipe-results').innerHTML=`<p class="recipe-count">${list.length} recipe${list.length===1?'':'s'} to make life easier</p>${list.map(r=>`<button type="button" class="recipe-result" data-recipe-open="${r.id}" data-slot="${recipeContext.slot}"><span class="recipe-emoji" aria-hidden="true">${foodEmoji[r.protein]}</span><span><strong>${esc(r.title)}</strong><small>${r.minutes} min · ${esc(r.cuisine)}</small><small>${r.allergens.length?'Contains '+r.allergens.join(', '):'Check ingredient labels for allergens'}</small></span><span aria-hidden="true">›</span></button>`).join('')||'<p class="empty">No matches. Try a different filter or check your excluded ingredients.</p>'}`;}
function recipeDetail(id,slot){const r=recipeById(id);if(!r)return;const planned=recipeFor(selected,slot)?.id===id;const servings=planned?currentWeek().meals[selected].recipes[slot].servings:mealServings(currentWeek(),selected,slot);const factor=servings/r.servings;modal(esc(r.title),`<div class="recipe-detail"><div class="recipe-heading"><span class="food-sticker">${foodEmoji[r.protein]}</span><p>${r.minutes} minutes · ${esc(r.cuisine)}<br>${servings} ${r.audience==='child'?'small portions':'adult servings'}</p></div><p class="allergen-label"><strong>Allergens:</strong> ${r.allergens.length?r.allergens.join(', '):'None identified in the listed basic ingredients'}. Check packaged products.</p><h3>Into the basket</h3><ul class="ingredient-list">${r.ingredients.map(i=>`<li><span>${esc(i.name)}</span><strong>${quantity(i.qty*factor)} ${esc(i.unit)}</strong></li>`).join('')}</ul><h3>Let’s make it</h3><ol class="recipe-steps">${r.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><p class="food-note">${esc(r.note)}</p>${r.audience==='child'?'<p class="food-note">Use full-fat plain dairy for children under two. For packing: follow the kindergarten’s storage and reheating rules. Keep chilled food cold with an ice pack; cool cooked rice quickly, refrigerate within one hour and use within 24 hours. Check fish carefully for bones and squash round foods such as peas.</p>':''}<div class="recipe-detail-actions"><button type="button" class="button ghost" data-recipe-fav="${id}">${(state.recipeFavorites||[]).includes(id)?'♥ Saved to favourites':'♡ Keep this recipe'}</button><button type="button" class="text-button" data-recipe-pick="${slot}">← More recipes</button></div></div><div class="form-actions"><button class="button lime" type="submit">${planned?'Keep on the menu':`Plan for ${fmt(selected,{weekday:'short'})}`}</button></div>`,()=>selectRecipe(r,slot,servings));$('#dialog').classList.add('recipe-dialog');}
function quantity(n){return Number.isInteger(n)?String(n):String(Math.round(n*100)/100);}
async function selectRecipe(r,slot,servings){if(r.audience==='child'&&slot!=='child')slot='child';if(r.audience==='adult'&&slot==='child')slot=r.slots[0]==='breakfast'?'breakfast':'dinner';return save(s=>{const m=s.weeks[week].meals[selected];m[slot]=r.title;m.recipes??={};m.recipes[slot]={id:r.id,servings};log(s,`Planned ${r.title} for ${fmt(selected,{weekday:'long'})}.`);},'Meal picked. Ingredients added to groceries.');}
function mealPortions(slot){const ref=currentWeek().meals[selected].recipes[slot];modal('How many are eating?',`<label>Servings<input type="number" name="servings" min="1" max="8" step="1" value="${ref.servings}" required></label><p class="form-hint">We’ll scale the grocery quantities. The recipe’s cooking method stays the same; larger batches may need more time or a second pan.</p>${actions('Update portions')}`,f=>save(s=>s.weeks[week].meals[selected].recipes[slot].servings=Number(f.get('servings')),'Portions and groceries updated.'));}
function shuffled(list){return [...list].map(r=>({r,n:Math.random()})).sort((a,b)=>a.n-b.n).map(x=>x.r);}
function generateMealPlan(s,key,includeChild){const w=s.weeks[key],used=new Set(),suggestions=[];let red=0,childFish=0;
 Object.values(w.meals).forEach(m=>Object.values(m.recipes||{}).forEach(ref=>{used.add(ref.id);const r=recipeById(ref.id);if(r?.audience==='adult'&&['Beef','Lamb'].includes(r.protein))red++;if(r?.audience==='child'&&r.protein==='Fish')childFish++;}));
 let lastDinner='';
 for(let day=0;day<7;day++){const ds=addDays(key,day);for(const slot of ['breakfast','lunch','dinner',...(includeChild?['child']:[])]){if(w.meals[ds][slot]?.trim())continue;if(slot==='lunch'&&w.work[ds].every(x=>x==='office'))continue;
 let list=shuffled(RECIPES.filter(r=>r.slots.includes(slot)&&isAllowed(r,s)&&!used.has(r.id)&&(!['Beef','Lamb'].includes(r.protein)||r.audience==='child'||red<1)&&(r.audience!=='child'||r.protein!=='Fish'||childFish<2)));
 if(slot==='dinner'){const different=list.filter(r=>r.protein!==lastDinner);if(different.length)list=different;}
 if(slot==='child'){const note=(w.kindergarten?.[ds]||'').toLowerCase();const match=list.filter(r=>note.split(/\W+/).some(word=>word.length>3&&(r.title+' '+r.protein).toLowerCase().includes(word)));if(match.length)list=match;}
 const r=list[0];if(!r)continue;used.add(r.id);if(r.audience==='adult'&&['Beef','Lamb'].includes(r.protein))red++;if(r.audience==='child'&&r.protein==='Fish')childFish++;if(slot==='dinner')lastDinner=r.protein;
 suggestions.push({day:ds,slot,id:r.id,servings:mealServings(w,ds,slot)});
 }}return suggestions;
}
function planWeek(){modal('Let’s take dinner off your mind',`<p class="welcome-copy">Fill empty meal slots for ${fmt(week,{day:'numeric',month:'short'})}–${fmt(addDays(week,6),{day:'numeric',month:'short'})}. Your existing choices stay put.</p><div class="food-note">We’ll vary proteins, avoid repeating recipes, and keep adult red-meat meals occasional. Lunch is skipped when you’re both at the office.</div><label class="check-label"><input type="checkbox" name="child">Also suggest ${esc(state.child)}’s lunches</label><p class="form-hint">Kindergarten notes guide simple recipe matching. Review toddler choices and allergens before using them.</p>${actions('Show me the week')}`,f=>{const suggestions=generateMealPlan(state,week,!!f.get('child'));if(!suggestions.length){toast('No empty slots or matching recipes. You can swap a meal individually.');return false;}showPlanPreview(suggestions);return false;});}
function showPlanPreview(suggestions){modal('A week with less guesswork',`<p class="form-hint">${suggestions.length} meals suggested. Add this draft, then swap anything that doesn’t sound good.</p><div class="plan-preview">${suggestions.map(x=>`<div><small>${fmt(x.day,{weekday:'short'})} · ${esc(mealNames[x.slot])}</small><strong>${esc(recipeById(x.id).title)}</strong></div>`).join('')}</div>${actions('Use this meal plan')}`,()=>save(s=>{for(const x of suggestions){const m=s.weeks[week].meals[x.day];if(m[x.slot]?.trim())continue;m[x.slot]=recipeById(x.id).title;m.recipes??={};m.recipes[x.slot]={id:x.id,servings:x.servings};}log(s,'Made a varied meal plan for the week.');},'The week is looking tasty. Your grocery list is ready.'));}
function groceryItems(s=state,key=week){const totals=new Map(),custom=[];const w=s.weeks[key];Object.entries(w.meals).forEach(([day,m])=>Object.keys(mealNames).forEach(slot=>{if(!m[slot]?.trim())return;const ref=m.recipes?.[slot],r=recipeById(ref?.id);if(!r||r.title!==m[slot]){custom.push(`${fmt(day,{weekday:'short'})} · ${m[slot]}`);return;}r.ingredients.forEach(i=>{const k=i.key+'|'+i.unit;const current=totals.get(k)||{...i,qty:0};current.qty+=i.qty*ref.servings/r.servings;totals.set(k,current);});}));return {items:[...totals.values()].map(i=>({...i,qty:Math.round(i.qty*100)/100,checkKey:i.key+'|'+quantity(i.qty)})),custom};}
function groceryView(){const {items,custom}=groceryItems();const checked=currentWeek().groceryChecked||{},extra=currentWeek().groceryExtras||[];const groups=['Vegetables','Herbs & aromatics','Meat & seafood','Eggs & dairy','Pantry','Spice cupboard'];return `<section class="food-intro"><span class="eyebrow">THE ONE-TRIP SHOP</span><h2>From your plan, into the basket.</h2><p>${fmt(week,{day:'numeric',month:'short'})}–${fmt(addDays(week,6),{day:'numeric',month:'short'})} · Quantities combine the whole week. Tick what you already have, too.</p><div class="setup-links"><button class="button light" data-food-action="copy-groceries">Copy list</button><button class="button light" data-food-action="extra">+ Add an extra</button></div></section>${!items.length?'<div class="empty">Choose a few recipes and your ingredients will appear here.</div>':''}${groups.map(group=>{const list=items.filter(i=>i.aisle===group);return list.length?`<section class="card grocery-group"><h3>${group}</h3>${list.map(i=>`<label class="grocery-item ${checked[i.checkKey]?'checked':''}"><input type="checkbox" data-grocery="${esc(i.checkKey)}" ${checked[i.checkKey]?'checked':''}><span>${esc(i.name)}</span><strong>${quantity(i.qty)} ${esc(i.unit)}</strong></label>`).join('')}</section>`:'';}).join('')}${extra.length?`<section class="card grocery-group"><h3>A few extras</h3>${extra.map(e=>`<label class="grocery-item"><input type="checkbox" data-grocery-extra="${e.id}" ${e.done?'checked':''}><span>${esc(e.text)}</span></label>`).join('')}</section>`:''}${custom.length?`<div class="food-note"><strong>Handwritten meals need your ingredient check:</strong><ul>${custom.map(t=>`<li>${esc(t)}</li>`).join('')}</ul></div>`:''}<p class="section-note">Amounts are recipe totals, not supermarket pack sizes. Fractional eggs can be rounded up when shopping; adjust small batches by eye. Check what’s already in your kitchen.</p>`;}
function kindergartenMenu(){modal('What’s on at kindergarten?',`<p class="form-hint">Copy the main lunch from their app. This stays with the week; no external app access is needed.</p><div class="form-stack">${days.map((day,i)=>{const ds=addDays(week,i);return `<label>${day} ${date(ds).getDate()}<input name="${ds}" value="${esc(currentWeek().kindergarten?.[ds]||'')}" maxlength="150" placeholder="e.g. Fish, potatoes and peas"></label>`;}).join('')}</div>${actions('Save the lunch brief')}`,f=>save(s=>{const w=s.weeks[week];w.kindergarten=Object.fromEntries(days.map((_,i)=>{const ds=addDays(week,i);return [ds,f.get(ds).trim()];}));},'Lunch brief saved. Ready to match some recipes.'));}
function foodPreferences(){const excluded=state.foodPrefs?.excludedAllergens||[];modal('Food that fits your household',`<p class="form-hint">Recipes with a checked allergen are hidden from suggestions and search. Existing meals are not removed. Always check ingredient labels and kindergarten rules.</p><fieldset class="allergen-fieldset"><legend>Exclude from recipe suggestions</legend>${['Egg','Milk','Fish','Shellfish','Wheat','Soy','Sesame','Mustard'].map(a=>`<label class="check-label"><input type="checkbox" name="allergen" value="${a}" ${excluded.includes(a)?'checked':''}>${a}</label>`).join('')}</fieldset><div class="food-note">Adult recipes emphasise protein and vegetables without measured macro claims. Toddler lunches include starches and fats; they are not adult diet meals. Recipes are original rough cooking guides, not individually dietitian-reviewed.</div><details class="food-sources"><summary>Lunchbox & toddler guidance</summary><p>Use familiar tolerated ingredients, soft textures, no whole nuts, and fully cooked eggs, meat and seafood. No raw carrot chunks; squash peas and check fish for bones.</p><p>Keep packed food chilled and follow the kindergarten’s reheating policy. Cool rice quickly, refrigerate within an hour, use within 24 hours and reheat only once until steaming hot; cool before serving.</p><a href="https://www.nhs.uk/baby/weaning-and-feeding/what-to-feed-young-children/" target="_blank" rel="noopener">NHS: feeding young children</a><a href="https://www.nhs.uk/best-start-in-life/baby/weaning/safe-weaning/preparing-food-safely/" target="_blank" rel="noopener">NHS: safe food preparation</a><a href="https://www.fda.gov/food/consumers/advice-about-eating-fish" target="_blank" rel="noopener">FDA: choosing fish for children</a><a href="https://www.food.gov.uk/sites/default/files/media/document/sfbb-childminders-pack_0_1.pdf" target="_blank" rel="noopener">FSA: safe food for childminders</a></details>${actions('Save food preferences')}`,f=>save(s=>s.foodPrefs={...(s.foodPrefs||{}),excludedAllergens:f.getAll('allergen')},'Food preferences saved.'));}
document.addEventListener('input',e=>{if(e.target.id==='recipe-search'){recipeSearch=e.target.value;updateRecipeResults();}});
document.addEventListener('change',e=>{const t=e.target;if(t.id==='recipe-protein'){recipeProtein=t.value;updateRecipeResults();}if(t.id==='recipe-quick'){recipeQuick=t.checked;updateRecipeResults();}if(t.id==='recipe-faves'){recipeFaves=t.checked;updateRecipeResults();}if(t.dataset.grocery)save(s=>{const w=s.weeks[week];w.groceryChecked??={};w.groceryChecked[t.dataset.grocery]=t.checked;});if(t.dataset.groceryExtra)save(s=>{s.weeks[week].groceryExtras.find(x=>x.id===t.dataset.groceryExtra).done=t.checked;});});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||person===null)return;if(b.dataset.foodPane){foodPane=b.dataset.foodPane;render();return;}if(b.dataset.recipePick)return recipePicker(b.dataset.recipePick);if(b.dataset.recipeOpen)return recipeDetail(b.dataset.recipeOpen,b.dataset.slot||'dinner');if(b.dataset.mealPortions)return mealPortions(b.dataset.mealPortions);if(b.dataset.recipeFav){const id=b.dataset.recipeFav;const ok=await save(s=>{s.recipeFavorites??=[];s.recipeFavorites=s.recipeFavorites.includes(id)?s.recipeFavorites.filter(x=>x!==id):[...s.recipeFavorites,id];});if(ok){b.textContent=(state.recipeFavorites||[]).includes(id)?'♥ Saved to favourites':'♡ Keep this recipe';toast('Recipe favourites updated.');}return;}
 const action=b.dataset.foodAction;if(action==='plan')planWeek();if(action==='kindergarten')kindergartenMenu();if(action==='preferences')foodPreferences();if(action==='favorites')recipePicker('dinner',true);if(action==='extra')modal('One more thing for the basket',`<label>What do you need?<input name="item" required maxlength="120" placeholder="e.g. 1 carton of milk"></label>${actions('Add to the list')}`,f=>save(s=>{const w=s.weeks[week];w.groceryExtras??=[];w.groceryExtras.push({id:uid(),text:f.get('item').trim(),done:false});},'Added to your grocery list.'));
 if(action==='copy-groceries'){const {items,custom}=groceryItems();const text=['Small Wins groceries',...items.map(i=>`${quantity(i.qty)} ${i.unit} ${i.name}`),...(currentWeek().groceryExtras||[]).filter(x=>!x.done).map(x=>x.text),...(custom.length?['Check handwritten meals:',...custom]:[])].join('\n');try{await navigator.clipboard.writeText(text);toast('Grocery list copied.');}catch{modal('Your grocery list',`<label>Copy this list<textarea rows="12" readonly>${esc(text)}</textarea></label>${actions('Done')}`,()=>true);}}
});
